#!/bin/python3

import pyautogui
import sys
from fls import *

folder = sys.argv[1]
offset = int(sys.argv[2]) if len(sys.argv) > 2 else 0

files = scandir(folder)

set_assets_dir(fls_dir() + '/.bandcamp_uploader')

for index, file in enumerate(files):

    if index < offset:
        continue

    while True:
        try:
            locate_and_click('add_track.png')
            break;
        except:
            pyautogui.press('down')
            sleep(1)

    pyautogui.write(file)
    sleep(1)

    pyautogui.press('enter')
    sleep(1)

    locate_and_click('track_name.png')

    pyautogui.write(file)
    pyautogui.press('tab')

    sleep(rand(8,15))
