#!/bin/bash

[[ -z $1 ]] && echo "Demo file not provided" && exit 1

sesspath=$(sudo php -r "echo session_save_path();")
sudo rm $sesspath/sess_* 2>/dev/null

name=$(echo ${1%.*})
index=${2:-index}

(sleep .1; xdg-open http://localhost:4311/$name/$index) &
php -S localhost:4311 demo_router.php
