#!/bin/php
<?php

$file = $argv[1];
$ext = pathinfo($file, PATHINFO_EXTENSION);

if(empty($ext)){
    foreach(['php','py','js'] as $ext){
        if(stream_resolve_include_path("$file.$ext")){
            $file = "$file.$ext";
            break;
        }
    }
}

switch($ext){
    case 'php':
        require $file;
        $func = str_replace(".$ext","",$file);
        $args = array_map(fn($arg) => json_decode($arg,true), array_slice($argv,2));
        echo $func(...$args);
    break;
    default:
        echo "No fcall handler for file: $file\n";
        exit(1);
}
