#!/bin/php
<?php

$file = $argv[1];
$ext = pathinfo($file, PATHINFO_EXTENSION);

if(empty($ext)){
    foreach(['php','py','js'] as $ext){
        if(stream_resolve_include_path("$file.$ext")){
            $file = "$file.$ext";
            break;
        }
    }
}

switch($ext){
    case 'php':
        require $file;
        $func = str_replace(".$ext","",$file);
        echo $func(...array_slice($argv,2));
    break;
    default:
        die("No funcall handler for file: $file\n");
}
