#!/bin/bash
set -e

ZIP_FILE=$1
BUCKET=$2
SUBDIR=${3:-}
EXTRACT_DIR="/tmp/zip2s3"

rm -rf "$EXTRACT_DIR" 2>/dev/null

# Extract
unzip "$ZIP_FILE" -d "$EXTRACT_DIR"

# Upload to S3
aws s3 cp "$EXTRACT_DIR/$SUBDIR" "s3://$BUCKET/" --recursive

# Clean up
rm -rf "$EXTRACT_DIR"
