#!/bin/bash

function expect {
    if [[ "$1" != "$2" ]]; then
        echo "Expected $1 to be $2";
        exit 1;
    fi;
}

ext="${1##*.}"


if [[ $ext == "php" ]]
then
    php ./test.php $1
else
    . ./$1
fi
