#!/bin/bash
. ../common

function expect {
    if [[ "$1" != "$2" ]]; then
        echo "Expected $1 to be $2";
        exit 1;
    fi;
}

function test_file {

    type=$(ext $1)

    if [[ $type == "php" ]]
    then
        php ./test.php $1
    elif [[ -z $type ]]
    then
        . ./$1
    else
        echo skipping $i
    fi
}

if [ ! -z $1 ]; then
    test_file $1
else
    for f in $(fls_dir)/*; do
        f=$(basename $f)
        if [[ -f $(fls_dir)/tests/$f ]]; then
            out=$(test_file $f 2>&1);
            [[ "$out" == *"skipping" ]] && continue;
            echo "Tested $f"
            [[ ! -z "$out" ]] && echo $out && break;
        fi;
    done;
fi
